import Head from "next/head";
import { Inter } from "@next/font/google";
import { useState } from "react";
import Link from "next/link";
import { FaCommentMedical } from 'react-icons/fa';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [result, setResult] = useState();
  const [condition, setcondition] = useState();

 const onSubmit = async (event) => {
  event.preventDefault();

  try {
    const response = await fetch("/api/condition", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ condition: condition }),
    });

    const data = await response.json();
    if (response.status !== 200) {
      throw data.error || new Error(`Request failed with status ${response.status}`);
    }

    setResult(data.result);
    setcondition("");
  } catch(error) {
    // Consider implementing your own error handling logic here
    console.error(error);
    alert(error.message);
  }
 }

  return (
    <>
      <Head>
        <title>DoctorAI - Get instant knowledge of your medical conditions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="text-gray-600 body-font flex justify-center items-center">
        <div className="container px-5 py-24 mx-auto">
          <div className="flex flex-col text-center w-full mb-12">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">
            <FaCommentMedical className="items-center m-auto text-indigo-500"/> DoctorAI - Developed by <Link className="text-indigo-500" href={'/asad'}>  Asad Ullah Khan</Link>
            </h1>
            <p className="lg:w-2/3 mx-auto leading-relaxed text-base">
              Medical Chat Bot Created with the help of ChatGPT Open AI.
            </p>
            <p className="lg:w-2/3 mx-auto leading-relaxed text-base">
              Get Answers to your Medical conditions and symptoms.
            </p>
          </div>
            <div className="p-2 w-full">
              <div className="relative">
                <label htmlFor="message" className="leading-7 text-sm text-gray-600">
                  Enter your Medical Condition here.
                </label>
                <form onSubmit={onSubmit}>
                  <textarea
                    onChange={(e) => {
                      setcondition(e.target.value);
                    }}
                    id="message"
                    name="message"
                    className="w-full bg-gray-100 bg-opacity-50 rounded border border-gray-300 focus:border-indigo-500 focus:bg-white focus:ring-2 focus:ring-indigo-200 h-32 text-base outline-none text-gray-700 py-1 px-3 resize-none leading-6 transition-colors duration-200 ease-in-out"
                  ></textarea>
                  <button className="flex mx-auto mt-6 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">
                    Ask MedChat
                  </button>
                </form>
              </div>
            </div>

         

          <div className="flex flex-col text-center w-full mb-12 mt-12">
            <h1 className="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">
              Suggestions
            </h1>
            <p className="lg:w-2/3 mx-auto leading-relaxed text-base text-2xl">
              {result}
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
